version: '3.3'



services:
<<<<<<< HEAD
  synapse:
=======
   synapse:
>>>>>>> 319f16f92914c9518090749ed7c02922032019e4
        image: matrixdotorg/synapse:latest
        restart: always
        ports: 
           - '8008:8008'
        volumes:
           - ./synapse/data/:/data/
        links:
           - postgres

  postgres:
        image: postgres:latest
        ports:
           - '5432:5432'
        restart: always
        environment:
            POSTGRES_USER: "matrix"
            POSTGRES_PASSWORD: "matrix"
            POSTGRES_DB: "synapse"
            POSTGRES_INITDB_ARGS: "--encoding='UTF8' --lc-collate='C' --lc-ctype='C'"
        volumes:
            - ./synapse/database/:/var/lib/postgresql/data/
